apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: deployhub
  labels:
    app.kubernetes.io/name: deployhub-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: deployhub-platform
spec:
  type: ClusterIP
  selector:
    app: deployhub-backend
  ports:
    - port: 8000
      targetPort: 8000
      name: http
      protocol: TCP
